---
apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.database.service.name }}

spec:
  type: {{ .Values.database.service.type }}

  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}

  selector:
    app: demo-db

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-db

  labels:
    app: demo-db

spec:
  replicas: 1

  selector:
    matchLabels:
      app: demo-db

  template:
    metadata:
      labels:
        app: demo-db

    spec:
      containers:
        - name: postgres
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.database.service.port }}

          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.name | quote }}

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: username

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: password

          resources:
            requests:
              cpu: {{ .Values.database.resources.requests.cpu | quote }}
              memory: {{ .Values.database.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.database.resources.limits.cpu | quote }}
              memory: {{ .Values.database.resources.limits.memory | quote }}

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: demo-db-pvc