---
apiVersion: v1
kind: Service

metadata:
  name: petclinic

spec:
  type: {{ .Values.service.type }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.petclinic.containerPort }}

  selector:
    app: petclinic

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: petclinic

  labels:
    app: petclinic

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: petclinic

  template:
    metadata:
      labels:
        app: petclinic

    spec:
      containers:
        - name: workload

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: SPRING_PROFILES_ACTIVE

            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: POSTGRES_URL

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: username

            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: password

            - name: SERVICE_BINDING_ROOT
              value: /bindings

            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true
                }

          ports:
            - name: http
              containerPort: {{ .Values.petclinic.containerPort }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http

          volumeMounts:
            - mountPath: /bindings/secret
              name: binding
              readOnly: true

      volumes:
        - name: binding
          projected:
            sources:
              - secret:
                  name: {{ .Values.secret.name }}