apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.secret.name }}

type: servicebinding.io/postgresql

stringData:
  type: "postgresql"

  provider: "postgresql"

  host: {{ .Values.database.service.name | quote }}

  port: {{ .Values.database.service.port | quote }}

  database: {{ .Values.database.name | quote }}

  username: {{ .Values.secret.username | quote }}

  password: {{ .Values.secret.password | quote }}